Repository cfengine/core, pull requests merged in 2018-06, with the labels that each got.

#3152 CFE-2832: Fixed segfault when giving invalid arguments to cf-net
  cf-net/cf-net.c
Labels: cherry-pick?

#3154 CFE-2793: Bundle name is now part of the log message when aborting a bundle
  libpromises/eval_context.c
Labels: cherry-pick?

#3158 Bundle name is now part of the log message when aborting a bundle (3.10)
  libpromises/eval_context.c
Labels: discussion, onhold

#3165 3.10.x - Increase the connection backlog/queue size in cf-serverd
  cf-serverd/cf-serverd-functions.c
Labels: onhold
