Repository cfengine/core, pull requests merged in 2020-06, with the labels that each got.

#4204 [3.15.x] cf-secret
  .gitignore
  Makefile.am
  cf-secret/Makefile.am
  cf-secret/README.md
  cf-secret/cf-secret.c
  configure.ac
  examples/cf-secret.cf
  examples/cf-secret.cf.cfcrypt
  examples/cf-secret.cf.priv
  examples/cf-secret.cf.pub
  libenv/sysinfo.c
  libpromises/lastseen.h
  tests/acceptance/27_cf-secret/decrypt.cf
  tests/acceptance/27_cf-secret/encrypt-decrypt-args.cf
  tests/acceptance/27_cf-secret/encrypt-decrypt.cf
  tests/acceptance/27_cf-secret/encrypt.x.cf
  tests/acceptance/27_cf-secret/encrypted
  tests/acceptance/27_cf-secret/plaintext
  tests/acceptance/27_cf-secret/testkey.priv
  tests/acceptance/27_cf-secret/testkey.pub
  tests/acceptance/testall
Labels: onhold

#4198 Remove race condition in WaitForCriticalSection()
  libpromises/Makefile.am
  libpromises/dbm_api.c
  libpromises/dbm_api.h
  libpromises/dbm_api_types.h
  libpromises/dbm_lmdb.c
  libpromises/dbm_priv.h
  libpromises/dbm_quick.c
  libpromises/dbm_tokyocab.c
  libpromises/locks.c
  tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf
Labels: cherry-pick?

#4229 LGTM: Fixed false positives in bool type mismatch query
  .lgtm/cpp-queries/bool-type-mismatch-return.ql
Labels: lgtm

#4224 verify_vars.c: Removed -1 returns from bool function
  libpromises/verify_vars.c
Labels: lgtm

#4230 LGTM: Fixed false positives in NULL check query
  .lgtm/cpp-queries/missing-argument-null-check.ql
Labels: lgtm

#4225 storage promises managing nfs mounts should now correctly mount after editing fstab entries
  cf-agent/nfs.c
  cf-agent/verify_storage.c
Labels: lgtm

#4223 cf3parse_logic.h: Fixed an int/bool function mismatch
  libpromises/cf3parse_logic.h
Labels: lgtm

#4222 Removed unnecessary copy of Attributes struct in mustache rendering
  cf-agent/verify_files.c
Labels: lgtm
